name: zzt
version: "3.2"
base: core18
summary: ZZT
description: |
  ZZT is an ANSI character-based video game, released in 1991 by Tim Sweeney
  of Potomac Computer Systems (now Epic Games).

confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: s309x

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

apps:
  zzt:
    command: launcher
    command-chain: ["snap/command-chain/alsa-launch"]
    plugs: [home, unity7, audio-playback, opengl, desktop, desktop-legacy]

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
    stage:
      # restrict to only audio-related files - you need to ensure
      # that gtk3 is staged for yad to work correctly, to prompt
      # users to connect the alsa plug or proceed with pulseaudio.
      #
      # This helps prevent symbol conflicts in situations where
      # you're using a non-default library, such as those that the
      # gnome-3-34 extension for core18 provides.
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasound*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdnsfile*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libFLAC*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjack*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpulse*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamplerate*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libspeex*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvorbis*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
  dosbox:
    after: [alsa-mixin]
    plugin: autotools
    source-type: tar
    source: http://source.dosbox.com/dosboxsvn.tgz
    build-packages:
      - g++
      - make
      - libsdl1.2-dev
      - libpng-dev
      - libsdl-net1.2-dev
      - libsdl-sound1.2-dev
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasyncns0
      - libcaca0
      - libflac8
      - libgl1
      - libglvnd0
      - libglx0
      - libmikmod3
      - libogg0
      - libopenal1
      - libpng16-16
      - libpulse0
      - libsdl-net1.2
      - libsdl-sound1.2
      - libsdl1.2debian
      - libsdl2-2.0-0
      - libglu1-mesa
      - libslang2
      - libsndfile1
      - libsndio6.1
      - libspeex1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb1
      - libxcursor1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxss1
      - libxxf86vm1
  zzt:
    plugin: dump
    source: snap/local/zzt.zip
    stage-packages:
      - libpng16-16
      - libsdl1.2debian
      - libsdl-net1.2
      - libsdl-sound1.2
      - libgl1-mesa-glx
      - libglu1-mesa
      - libslang2
      - freeglut3
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
  integration:
    plugin: dump
    source: snap/local/scripts
